title: World Coffee Tour
author: Joe Gaudet
email:
description: >-
  What started as a way to honor a friend who passed away, became a way to explore the world, one cup of coffee at a time.
baseurl: ""
url: "https://worldcoffeetour.joegaudet.com"
instagram_username: joegaudet

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  coffee_posts:
    output: true
    permalink: /coffee/:path/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CLAUDE.md